package:
  name: libobjcryst
  ## Use __conda_version__.txt.
  # version: 2015.1a1

source:
  git_url: https://github.com/diffpy/libobjcryst.git
  git_rev: v2015.1a1

build:
  number: 0
  binary_relocation: False      # [linux]

requirements:
  build:
    - scons
    - boost                     # [linux]
    - boost 1.56.0 py27_2       # [osx]

about:
  home: https://github.com/diffpy/libobjcryst/
  license: GPLv2
  license_file: LICENSE.txt
